version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=Ecommerce
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./Backend/Backend/db-init:/docker-entrypoint-initdb.d
      - ecommerce-ps-data:/var/lib/postgresql/data

volumes:
  ecommerce-ps-data: